<?php
	 global $data;	
 	 global $TheChameleon_options;  

	 $year 				  = date('Y');
	 $get_theme_copyright = ( !empty( $TheChameleon_options ) and !empty( $TheChameleon_options['copyright'] ) ) ? $TheChameleon_options['copyright'] : 'Copyright © ' . date('Y') . ' ' . get_bloginfo('name').' | <span class="copyright">Generated by <a href="http://www.chameleonthemes.net/">The Chameleon Theme</a></span>';	
?>	

	<p><?php echo str_replace( "%year%", $year, $get_theme_copyright ); ?></p>
